# data
dataset: "warehouse-nn"
data_root: "/work3/s202821/data/interim"
collections: [
  # "2022-09-23-10-17-46",
  # "2022-09-23-10-39-51",
  # "2022-09-23-11-03-28",
  # "2022-09-23-11-09-28",
  "2022-10-19-10-44-31",
  # "2022-10-19-11-07-11",
  # "2022-10-19-11-15-59",
  # "2022-10-19-11-20-39"
]
split_ratio: [0.7, 0.2, 0.1]
detection_classes: 5 # including background
segmentation_classes: 2 # including background

# training pipeline
model_out_path: "models"
model: "frcnn" # [deeplabv3, ssdlite, frcnn(-resnet), frcnn-hybrid, ssdlite-hybrid]
attribute: "debug" # optional description, can be left empty
weight: "uncertainty" # [equal, uncertainty, dynamic, constant]
w_constant: [1.0, 1.0] # detetion, segmentation

# callbacks
optimizer:
  name: "adam"
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
lr_scheduler:
  name: "steplr" # can be None
  step_size: 3
  gamma: 0.1
early_stop:
  delta: 0.0000
  patience: 5

# augmentation
vflip:
  apply: False
  p: 0.5
hflip:
  apply: False
  p: 0.1
rotate:
  apply: False
  p: 0.1
  limit: 30
normalize:
  apply: False # not implemented denormalization yet
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  max_pixel_value: 255.0


# loader
batch_size: 2 # minimum 2 for deeplabv3
num_workers: 0
shuffle: True
max_epochs: 50
class_metrics: False

# logging
logging: False
wandb_project: "multitask-mayhem"
entity: "thesis-mayhem"
local_logs: ".logging"
sanity_epoch: 5 # logging validation images every n epochs
sanity_num: 5 # number of images to log

# debug
debug: True # no checkpoints or weights saved