# data
dataset: "warehouse-nn"
data_root: "../../../../../../work3/s202821/data/interim"
collections: [
  # "2022-09-23-10-17-46",
  # "2022-09-23-10-39-51", # not fully finished
  # "2022-09-23-11-03-28", # FIXME: missing images wrong sampling
  # "2022-09-23-11-09-28",
  "2022-10-19-10-44-31",
  "2022-10-19-11-07-11",
  # "2022-10-19-11-15-59",
  # "2022-10-19-11-20-39"
]
split_ratio: [0.7, 0.2, 0.1]
num_classes: 5 # including background

# training pipeline
model_out_path: "models"
model: "fasterrcnn"
attribute: "dummy" # optional, can be left empty
optimizer:
  name: "sgd"
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
batch_size: 1
num_workers: 0
shuffle: True
max_epochs: 30

# logging
logging: False
wandb_project: "mtl-mayhem"

# debug
debug: True # no checkpoints or weights saved