# data
dataset: "warehouse-nn"
data_root: "data/interim"
collections: [
  # "2022-09-23-10-17-46",
  # "2022-09-23-10-39-51",
  # "2022-09-23-11-03-28",
  # "2022-09-23-11-09-28",
  # "2022-10-19-10-44-31",
  # "2022-10-19-11-07-11",
  "2022-10-19-11-15-59",
  "2022-10-19-11-20-39"
]
split_ratio: [0.7, 0.2, 0.1]

# training pipeline
model_out_path: "models"
model: "fasterrcnn"
attribute: # optional, leave empty
optimizer:
  name: "sgd"
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
batch_size: 2
num_workers: 0
shuffle: False
# logging
logging: False
wandb_project: "mtl-mayhem"