# data
dataset: "warehouse-nn"
data_root: "/work3/s202821/data/interim"
collections: [
  "2022-09-23-10-17-46",
  "2022-09-23-10-39-51",
  "2022-09-23-11-03-28",
  "2022-09-23-11-09-28",
  "2022-10-19-10-44-31",
  "2022-10-19-11-07-11",
  "2022-10-19-11-15-59",
  "2022-10-19-11-20-39"
]
split_ratio: [0.7, 0.2, 0.1]
detection_classes: 5 # including background
segmentation_classes: 2 # including background

# training pipeline
model_out_path: "models"
model: "ssdlite"
attribute: "adam_optim" # optional, can be left empty

# callbacks
optimizer:
  name: "adam"
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
lr_scheduler:
  name: "steplr" # can be None
  step_size: 3
  gamma: 0.1
early_stop:
  delta: 0.0000
  patience: 3

# loader configs
batch_size: 2
num_workers: 4
shuffle: True
max_epochs: 30

# logging
logging: True
wandb_project: "multitask-mayhem"
entity: "thesis-mayhem"
local_logs: ".logging"

# debug
debug: False # no checkpoints or weights saved