# data
dataset: warehouse-nn
data_root: /work3/s202821/data/interim
test_manifest: /work3/s202821/data/test/manifest.json
collections: [
  2022-09-23-10-17-46,
  2022-09-23-10-39-51,
  2022-09-23-11-03-28,
  2022-09-23-11-09-28,
  2022-10-19-10-44-31,
  2022-10-19-11-07-11,
  2022-10-19-11-15-59,
  2022-10-19-11-20-39
]
split_ratio: [0.8, 0.2]
detection_classes: 5 # including background
segmentation_classes: 2 # including background

# training pipeline
model_out_path: /work3/s202821/models
model: ssdlite # [deeplabv3, ssdlite, frcnn(-resnet), frcnn-hybrid, ssdlite-hybrid]
attribute: # optional description, can be left empty
weight: # [equal, constant, uncertainty, dynamic, autol]
w_constant: # contant weighting values (float) [detection, segmentation]
grad_method: # [None, graddrop, pcgrad, cagrad]
temperature:

# callbacks
optimizer:
  name: adam
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
lr_scheduler:
  name: steplr # leave empty if not needed
  step_size: 8
  gamma: 0.1
  milestones:
early_stop:
  delta: 0.000
  patience: 10

# augmentation
vflip:
  apply: True
  p: 0.5
hflip:
  apply: False
  p: 0.1
rotate:
  apply: True
  p: 0.1
  limit: 30
normalize:
  apply: False # not implemented denormalization yet
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  max_pixel_value: 255.0


# loader
batch_size: 8 # minimum 2 for deeplabv3
num_workers: 4
shuffle: True
max_epochs: 100
class_metrics: False

# logging
logging: True
wandb_project: multitask-mayhem
entity: thesis-mayhem
local_logs: .logging
sanity_epoch: 5 # logging validation images every n epochs
sanity_num: 5 # number of images to log

# debug
debug: False # no checkpoints or weights saved